export const GET_ALL_DOGS = 'GET_ALL_DOGS';
export const GET_DOG_BY_ID = 'GET_DOG_BY_ID';
export const GET_DOGS_BY_NAME = 'GET_DOGS_BY_NAME';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';

export const FILTER_BY_ORIGN = 'FILTER_BY_ORIGN';
export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';

export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT'

export const REFRESH = 'REFRESH';
